# Generated by Django 4.0.5 on 2022-08-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NormalModel',
            new_name='AverageModel',
        ),
    ]
